name: Build Toolchain Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build toolchain image
        run: docker build -t trimui-smart-pro-toolchain .

      - name: Build your project inside container
        run: |
          mkdir -p workspace
          docker run --rm \
            -u toolchain \
            -v ${{ github.workspace }}/workspace:/home/toolchain/workspace \
            trimui-smart-pro-toolchain \
            bash -c "
              cd /home/toolchain/workspace/your_project && \
              echo '开始编译...' && \
              make || echo '⚠️ 请根据项目修改构建命令'
            "

      - name: List built binaries
        run: |
          echo "=== 编译产物 ==="
          find workspace -type f -executable || echo "❌ 没有找到二进制文件"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trimui-binaries
          path: workspace
