name: Build Toolchain

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t toolchain .

      # 4. 构建工具链
      - name: Build toolchain
        run: make shell || true

      # 5. 在容器中编译源码
      - name: Build inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/workspace:/root/workspace \
            toolchain \
            bash -c "cd /root/workspace && make build || echo '请在这里修改为正确的构建命令'"

      # 6. 上传产物（修复新版 v4）
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: workspace
          compression-level: 6
