name: Build Toolchain

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t toolchain .

      # 4. 在容器中执行构建
      #    workspace 映射到 /root/workspace
      - name: Build project inside container
        run: |
          mkdir -p workspace
          docker run --rm \
            -v ${{ github.workspace }}/workspace:/root/workspace \
            toolchain \
            bash -c "
              cd /root/workspace && \
              echo '开始构建项目...' && \
              # 如果项目有源码，这里执行编译命令
              make build || echo '请根据需要修改构建命令'
            "

      # 5. 检查 workspace 目录内容
      - name: Check workspace
        run: ls -R workspace || echo "workspace is empty"

      # 6. 上传产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: workspace
          compression-level: 6
