name: Build Toolchain

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t trimui-toolchain .

      # 4. 在容器中执行构建
      - name: Build inside container
        run: |
          mkdir -p workspace
          docker run --rm \
            -v ${{ github.workspace }}/workspace:/home/toolchain/workspace \
            trimui-toolchain \
            bash -c "
              cd /home/toolchain/workspace && \
              echo '开始构建项目...' && \
              make build || echo '请在这里修改为正确的构建命令'
            "

      # 5. 检查 workspace 内容
      - name: Check workspace files
        run: ls -R workspace || echo "workspace is empty"

      # 6. 上传编译产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: workspace
          compression-level: 6
